# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '08.remoteControll' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 08.remoteControll
  pod 'FirebaseRemoteConfig'
  pod 'FirebaseAnalytics'

end
