# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '08. COVID19' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Charts'

  # Pods for 08. COVID19

end
